### ISSUE TITLE
Asset bundle deploy - zip file already exists

### ISSUE THREAD

**Issue by johalnes** [databricks/setup-cli#97]
Hi,

I'm using this action together with Asset bundles (GitHub file below). Installation works as expected, but during deploy I get 
```bash 
Run databricks bundle deploy
Uploading bundle files to /Production/risk_analytics/files...
Error: file already exists: /Production/risk_analytics/files/databricks_cli_0.217.1_linux_amd64.zip"
```
Just by adding a step with `rm databricks_cli_0.217.1_linux_amd64.zip` solves the issue. 

Should one either change directory, like instal.sh that uses temp directory, or add a step to remove installation files?

``` bash
jobs:
  deploy:
    name: Production DBT run
    runs-on: ubuntu-latest  # self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.0
      
      - name: Install Databricks
        uses: databricks/setup-cli@main

      - name: Deploy Dataflows
        run: databricks bundle deploy 
        env:
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
          DATABRICKS_BUNDLE_ENV: prod
```

**Comment by pietern** [comment]
Thanks for reporting. I haven't heard about this before.

Are you sure that the zip file is coming from the action and isn't checked into the repository?

**Comment by johalnes** [comment]
hehe had't thought about that one actually. Would have been embarrassing! Luckily I didn't have it checked in 🙂 

Would suspect that would make the install step fail, and not the deploy asset bundle step?

**Comment by pietern** [comment]
Thanks for the additional reports. I confirmed the issue and have a fix in #113.

**Comment by pietern** [comment]
@dane-marjanovic There are two cases that I can think of when this is not happening, even in the current setup. First, if `*.zip` is part of your `.gitignore` file, it won't be part of the list of files to synchronize into the workspace. Second, if your bundle root directory is not at the root of the repository but in a subdirectory, the ZIP file won't ever be considered for file synchronization.

The issue here happens only for bundles that are located in the root of a repository, that don't ignore ZIP files by default.

**Comment by pietern** [comment]
The fix has been merged. If you're using the action from the main branch then it should now work.
